CREATE TABLE IF NOT EXISTS conversations (
    `id` VARCHAR(100) NOT NULL PRIMARY KEY,
    `user_id` VARCHAR(100) NOT NULL,
    `title` VARCHAR(255),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `IDX_CONVERSATIONS_USER_UPDATED` (`user_id`, `updated_at`)
);